title: Hobby Homepage
tagline: A website dedicated to some of my hobby projects.
description: A website dedicated to some of my hobby projects.
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
